# Generated by Django 2.1.2 on 2019-01-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_country',
        ),
        migrations.DeleteModel(
            name='user_register',
        ),
        migrations.DeleteModel(
            name='user_state',
        ),
    ]
