# Generated by Django 2.1.2 on 2019-01-16 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_login',
        ),
        migrations.DeleteModel(
            name='user_register',
        ),
    ]
