# Generated by Django 2.1.2 on 2019-01-16 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_login_user_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_hobby',
        ),
    ]
