# Generated by Django 2.1.2 on 2019-01-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_user_hobby'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Hobby', models.CharField(max_length=20)),
            ],
        ),
    ]
