# Generated by Django 2.1.2 on 2019-01-17 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_hobby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_register',
            old_name='Age',
            new_name='DOB',
        ),
    ]
