# Generated by Django 2.1.2 on 2019-01-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190117_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_register',
            name='DOB',
            field=models.CharField(max_length=20),
        ),
    ]
