# Generated by Django 2.1.2 on 2019-01-17 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190117_1134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_mailcompose_tb',
        ),
    ]
