# Generated by Django 2.1.2 on 2019-01-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_delete_user_mailcompose_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_mailcompose_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=20)),
                ('To', models.CharField(max_length=20)),
                ('Subject', models.CharField(max_length=20)),
                ('Content', models.CharField(max_length=500)),
            ],
        ),
    ]
