# Generated by Django 2.1.2 on 2019-01-18 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_delete_user_mailcompose_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_mailcompose_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=20)),
                ('Subject', models.CharField(max_length=20)),
                ('Content', models.CharField(max_length=500)),
                ('Date', models.CharField(max_length=20)),
                ('To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_register')),
            ],
        ),
    ]
