# Generated by Django 2.1.2 on 2019-01-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_mailcompose_tb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_mailcompose_tb',
            name='To',
        ),
        migrations.DeleteModel(
            name='user_mailcompose_tb',
        ),
    ]
