# Generated by Django 2.1.2 on 2019-01-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_user_mailcompose_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_mailsave_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.IntegerField()),
                ('To', models.IntegerField()),
                ('Subject', models.CharField(max_length=20)),
                ('Content', models.CharField(max_length=500)),
                ('Date', models.CharField(max_length=20)),
            ],
        ),
    ]
