# Generated by Django 2.1.2 on 2019-01-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20190121_1124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_mailsave_tb',
        ),
    ]
