# Generated by Django 2.1.2 on 2019-01-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_delete_user_mailsave_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_mailsave_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.IntegerField()),
                ('From', models.CharField(max_length=20)),
                ('Subject', models.CharField(max_length=20)),
                ('Content', models.CharField(max_length=500)),
                ('Date', models.CharField(max_length=20)),
            ],
        ),
    ]
