# Generated by Django 2.1.5 on 2019-01-28 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_user_mailsave_tb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_mailsave_tb',
        ),
    ]
