# Generated by Django 2.1.5 on 2019-01-28 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_user_mailsave_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.IntegerField()),
                ('Contact_id', models.IntegerField()),
                ('Date', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_spam_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.IntegerField()),
                ('From', models.CharField(max_length=20)),
                ('Subject', models.CharField(max_length=20)),
                ('Content', models.CharField(max_length=500)),
                ('Date', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='user_mailcompose_tb',
            name='From',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_hobby'),
        ),
        migrations.DeleteModel(
            name='user_register',
        ),
    ]
