# Generated by Django 2.1.5 on 2019-01-28 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20190128_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('DOB', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=20)),
                ('Country', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('District', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('E_mail', models.CharField(max_length=20)),
                ('Phone_No', models.IntegerField()),
                ('Age', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user_mailcompose_tb',
            name='From',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_register'),
        ),
    ]
