# Generated by Django 2.1.5 on 2019-01-28 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20190128_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_register',
            name='Age',
        ),
    ]
