# Generated by Django 2.1.5 on 2019-01-28 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_remove_user_register_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_mailcompose_tb',
            name='From',
        ),
        migrations.DeleteModel(
            name='user_mailsave_tb',
        ),
        migrations.DeleteModel(
            name='user_mailcompose_tb',
        ),
    ]
