# Generated by Django 2.1.5 on 2019-01-29 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_user_mailcompose_tb_user_mailsave_tb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_login',
        ),
        migrations.AlterField(
            model_name='user_mailcompose_tb',
            name='From',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_hobby'),
        ),
        migrations.DeleteModel(
            name='user_register',
        ),
    ]
