# Generated by Django 2.1.5 on 2019-01-29 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20190129_1056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_spam_tb',
        ),
    ]
