# Generated by Django 2.1.5 on 2019-02-11 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_delete_user_spam_tb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_mailcompose_tb',
            name='From',
        ),
        migrations.RemoveField(
            model_name='user_mailsave_tb',
            name='Mail_id',
        ),
        migrations.DeleteModel(
            name='user_mailcompose_tb',
        ),
        migrations.DeleteModel(
            name='user_mailsave_tb',
        ),
    ]
