# Generated by Django 2.1.5 on 2019-02-11 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_auto_20190211_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_mailcompose_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('To', models.IntegerField()),
                ('Subject', models.CharField(max_length=20)),
                ('Content', models.CharField(max_length=500)),
                ('Date', models.CharField(max_length=20)),
                ('File', models.FileField(upload_to='')),
                ('Status', models.CharField(max_length=20)),
                ('From', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_register')),
            ],
        ),
        migrations.CreateModel(
            name='user_mailsave_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.IntegerField()),
                ('Mail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_mailcompose_tb')),
            ],
        ),
    ]
