# Generated by Django 2.1.5 on 2019-02-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_user_mailcompose_tb_user_mailsave_tb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contacts_tb',
        ),
        migrations.DeleteModel(
            name='user_hobby',
        ),
        migrations.DeleteModel(
            name='user_login',
        ),
        migrations.RemoveField(
            model_name='user_mailcompose_tb',
            name='From',
        ),
        migrations.RemoveField(
            model_name='user_mailsave_tb',
            name='Mail_id',
        ),
        migrations.DeleteModel(
            name='user_mailcompose_tb',
        ),
        migrations.DeleteModel(
            name='user_mailsave_tb',
        ),
        migrations.DeleteModel(
            name='user_register',
        ),
    ]
