# Generated by Django 2.1.5 on 2019-02-25 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0033_auto_20190225_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.IntegerField()),
                ('Contact_id', models.IntegerField()),
                ('Date', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Hobby', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Security_Ques', models.CharField(max_length=50)),
                ('Answer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_mailcompose_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('To', models.IntegerField()),
                ('Subject', models.CharField(max_length=20)),
                ('Content', models.CharField(max_length=500)),
                ('Date', models.CharField(max_length=20)),
                ('File', models.FileField(upload_to='')),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_mailsave_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.IntegerField()),
                ('Mail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_mailcompose_tb')),
            ],
        ),
        migrations.CreateModel(
            name='user_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('DOB', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=20)),
                ('Country', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('District', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('E_mail', models.CharField(max_length=20)),
                ('Phone_No', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user_mailcompose_tb',
            name='From',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_register'),
        ),
    ]
