# Generated by Django 2.2.5 on 2019-10-09 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_auto_20190225_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_mailcompose_tb',
            name='From',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
